//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignmentt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public int id { get; set; }
        public Nullable<int> iddh { get; set; }
        public string tensach { get; set; }
        public decimal gia { get; set; }
        public int soluong { get; set; }
        public string hinhanh { get; set; }
    }
}
