//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignmentt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        public int id { get; set; }
        public System.DateTime ngaydh { get; set; }
        public Nullable<int> idkh { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public decimal tonggia { get; set; }
    }
}
